order:
  sales_flat_order:
    columns:
      customer_email:
        formatter: email
        unique: true
        nullColumnBeforeRun: true
      customer_firstname:
        formatter:
        name: firstName
      customer_lastname:
        formatter:
        name: lastName
      customer_dob:
        formatter: dateTimeThisCentury
        optional: true
      customer_taxvat:
        formatter: vat
        optional: true
      remote_ip:
        formatter:
        name: ipv4
      customer_note:
        formatter: sentence
        optional: true

  sales_flat_order_grid:
    columns:
      shipping_name:
        formatter:
        name: name
      billing_name:
        formatter: name

  sales_flat_order_address:
    columns:
      email:
        formatter: email
        unique: true
        nullColumnBeforeRun: true
      firstname:
        formatter:
        name: firstName
      lastname:
        formatter:
        name: lastName
      company:
        formatter: company
        optional: true
      street:
        formatter:
        name: streetAddress
      city:
        formatter:
        name: city
      postcode:
        formatter:
        name: postcode
      telephone:
        formatter:
        name: phoneNumber
      fax:
        formatter: phoneNumber
        optional: true
      vat_id:
        formatter: vat
        optional: true