shipment:
  sales_flat_shipment_comment:
    columns:
      comment:
        formatter: sentence
        optional: true

  sales_flat_shipment_grid:
    columns:
      shipping_name:
        formatter:

    name: name

  sales_flat_shipment_track:
    columns:
      track_number:
        formatter: randomNumber