customer_address:
    customer_address: { columns: { company: { formatter: company }, first_name: { formatter: first_name }, last_name: { formatter: last_name }, title: { formatter: prefixMale }, street: { formatter: street }, zipcode: { formatter: zipcode }, city: { formatter: city }, phone_number: { formatter: phone } } }
